github: []  # 如果你有 GitHub Sponsors 账号，可以填入，例如 [your-github-username]
patreon: MeeGooBoo
open_collective: 
ko_fi: 
tidelift: 
community_bridge: 
liberapay: 
issuehunt: 
lfx_crowdfunding: 
polar: 
buy_me_a_coffee: 
thanks_dev: 
custom: 
  - https://paypal.me/MoGuoBiao  # PayPal 资助链接
  - https://www.patreon.com/meegooboo/membership
  - bitcoin:bc1qkwrq5plek62fmfaynyphfuuepm6cxd4fsh5wrp  # 比特币地址
